on:
  push:
    branches: ["main"]
    
permissions: write-all
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Python packages
        run: |
          pip install PyGithub pandas mistletoe lxml beautifulsoup4
      - name: Generate JSON
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python generate_json.py -t ${{ secrets.GH_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          commit_message: Automated Change
          commit_options: '--no-verify --signoff'
          file_pattern: 'apps.json apps_esign.json bundleId.csv icons/*'

          commit_user_name: My GitHub Actions Bot
          commit_user_email: my-github-actions-bot@example.org
          commit_author: Author <actions@github.com>

          push_options: '--force'
